const allItems = [
  {
    title: 'Pizza',
    img: 'images/margarita.jpg',
    price: 'Item: Price',
    description: 'Pizza with:',
  },
  {
    title: 'Pizza',
    img: 'images/margarita.jpg',
    price: 'Item: Price',
    description: 'Pizza with: ',
  },
  {
    title: 'Pizza',
    img: 'images/margarita.jpg',
    price: '240 MKD',
    description: 'Pizza with:',
  },
  {
    title: 'Pizza',
    img: 'images/margarita.jpg',
    price: '220 MKD',
    description: 'Pizza with:',
  },
  {
    title: 'Pizza',
    img: 'images/margarita.jpg',
    price: 'Item: Price',
    description: 'Pizza with:',
  },
  {
    title: 'Meats',
    img: 'images/mishra.jpg',
    price: 'Item: Price',
    description: 'Meat:',
  },
  {
    title: 'Meats',
    img: 'images/mishra.jpg',
    price: 'Item: Price',
    description: 'Meat:',
  },
  {
    title: 'Meats',
    img: 'images/mishra.jpg',
    price: 'Item: Price',
    description: 'Meat:',
  },
  {
    title: 'Meats',
    img: 'images/mishra.jpg',
    price: 'Item: Price',
    description: 'Meat:',
  },
  {
    title: 'Meats',
    img: 'images/mishra.jpg',
    price: 'Item: Price',
    description: 'Meat:',
  },
  {
    title: 'Pasta',
    img: 'images/pasta.jpg',
    price: 'Item: Price',
    description: 'Pasta with:',
  },
  {
    title: 'Pasta',
    img: 'images/pasta.jpg',
    price: 'Item: Price',
    description: 'Pasta with:',
  },
  {
    title: 'Pasta',
    img: 'images/pasta.jpg',
    price: 'Item: Price',
    description: 'Pasta with:',
  },
  {
    title: 'Salads',
    img: 'images/sallata.jpg',
    price: 'Item: Price',
    description: 'Sallad with:',
  },
  {
    title: 'Salads',
    img: 'images/sallata.jpg',
    price: 'Item: Price',
    description: 'Sallad with:',
  },
  {
    title: 'Salads',
    img: 'images/sallata.jpg',
    price: '170 MKD',
    description: 'Sallad with:',
  },
  {
    title: 'Salads',
    img: 'images/sallata.jpg',
    price: 'Item: Price',
    description: 'Sallad with:',
  },
  {
    title: 'Salads',
    img: 'images/sallata.jpg',
    price: 'Item: Price',
    description: 'Sallad with:',
  },
  {
    title: 'Salads',
    img: 'images/sallata.jpg',
    price: 'Item: Price',
    description: 'Sallad with:',
  },
  {
    title: 'Dessert',
    img: 'images/OIP.jpg',
    price: 'Item: Price',
    description: 'Dessert',
  },
  {
    title: 'Dessert',
    img: 'images/OIP.jpg',
    price: 'Item: Price',
    description: 'Dessert',
  },
  {
    title: 'Dessert',
    img: 'images/OIP.jpg',
    price: 'Item: Price',
    description: 'Dessert',
  },
  {
    title: 'Dessert',
    img: 'images/OIP.jpg',
    price: 'Item: Price',
    description: 'Dessert',
  },
  {
    title: 'Dessert',
    img: 'images/OIP.jpg',
    price: 'Item: Price',
    description: 'Dessert',
  },
]
export default allItems
