const allItems = [
  {
    title: 'Pizza',
    img: 'images/margarita.jpg',
    price: 'Pizza Margarita: 200 MKD',
    description: 'Salcë domatesh, Kaçkavall, Salamë',
  },
  {
    title: 'Pizza',
    img: 'images/margarita.jpg',
    price: 'Pizza e perzier: 280 MKD',
    description: 'Salcë domatesh, Kaçkavall, Proshutë, Salamë',
  },
  {
    title: 'Pizza',
    img: 'images/margarita.jpg',
    price: 'Pizza Tonno: 240 MKD',
    description: 'Salcë domatesh, Kaçkavall, Tono, Qepë',
  },
  {
    title: 'Pizza',
    img: 'images/margarita.jpg',
    price: 'Pizza Proshutë: 220 MKD',
    description: 'Salcë domatesh, Kaçkavall, Proshutë',
  },
  {
    title: 'Pizza',
    img: 'images/margarita.jpg',
    price: 'Pizza Vegjetariane: 260 MKD',
    description: 'Salcë domatesh, Kaçkavall, Speca, Brokoli, Këpurdha',
  },
  {
    title: 'Mishra',
    img: 'images/mishra.jpg',
    price: 'Fileto Pule: 280 MKD',
    description: 'Fileto pule',
  },
  {
    title: 'Mishra',
    img: 'images/mishra.jpg',
    price: 'Kotlet Vici: 450 MKD',
    description: 'Kotlet viçi me garnir',
  },
  {
    title: 'Mishra',
    img: 'images/mishra.jpg',
    price: 'Biftek: 900 MKD',
    description: 'Biftek me sos këpurdhash dhe garnir',
  },
  {
    title: 'Mishra',
    img: 'images/mishra.jpg',
    price: 'Zgarë e përzier: 1200 MKD',
    description: 'Bërxollë, Stek pule, Suxhuk',
  },
  {
    title: 'Mishra',
    img: 'images/mishra.jpg',
    price: 'Mish Viçi: 1000 MKD',
    description: 'Mish nga viçi',
  },
  {
    title: 'Pasta',
    img: 'images/pasta.jpg',
    price: 'Pasta Bolonjeze: 260 MKD',
    description: 'Salcë domatesh, Mish i bluar, Qepë',
  },
  {
    title: 'Pasta',
    img: 'images/pasta.jpg',
    price: 'Pasta Karbonara: 280 MKD',
    description: 'Sos këpurdhash, Salcë, Proshutë',
  },
  {
    title: 'Pasta',
    img: 'images/pasta.jpg',
    price: 'Pasta Arabiata: 220 MKD',
    description: 'Salcë domatesh, Hudhër, Ullinjë, Djegës',
  },
  {
    title: 'Sallatë',
    img: 'images/sallata.jpg',
    price: 'Sallatë Verore: 180 MKD',
    description: 'Filetë Pule, Marullë, Domate, Kastravec, Karrotë',
  },
  {
    title: 'Sallatë',
    img: 'images/sallata.jpg',
    price: 'Sallatë Shope: 140 MKD',
    description: 'Domate, Kastravec, Djath',
  },
  {
    title: 'Sallatë',
    img: 'images/sallata.jpg',
    price: 'Sallatë Greke: 170 MKD',
    description: 'Domate, Kastravec, Qepë, Ullinj, Djath',
  },
  {
    title: 'Sallatë',
    img: 'images/sallata.jpg',
    price: 'Sallatë E perzier: 170 MKD',
    description: 'Lakër, Marullë, Domate, Kastravec, Karrota, Sos i bardhë',
  },
  {
    title: 'Sallatë',
    img: 'images/sallata.jpg',
    price: 'Sallatë Tonno: 170 MKD',
    description: 'Marullë, Tono, Qepë',
  },
  {
    title: 'Sallatë',
    img: 'images/sallata.jpg',
    price: 'Sallatë Ulqin: 200 MKD',
    description: 'Proshut, Djath, Marullë, Domate, Karrotë, Ulinjë',
  },
  {
    title: 'Dessert',
    img: 'images/OIP.jpg',
    price: 'Trileqe: 50 MKD',
    description: 'Dessert',
  },
  {
    title: 'Dessert',
    img: 'images/OIP.jpg',
    price: 'Snickers: 60 MKD',
    description: 'Dessert',
  },
  {
    title: 'Dessert',
    img: 'images/OIP.jpg',
    price: 'Bounty: 60 MKD',
    description: 'Dessert',
  },
  {
    title: 'Dessert',
    img: 'images/OIP.jpg',
    price: 'Cheese Cake: 60 MKD',
    description: 'Dessert',
  },
  {
    title: 'Dessert',
    img: 'images/OIP.jpg',
    price: 'Bakllava: 40 MKD',
    description: 'Dessert',
  },
]
export default allItems
